### ISSUE TITLE
Mystery Events showing "via GTM"

### ISSUE THREAD

**Issue by rptomey** [sean-adams/dataslayer#58]
I've noticed lately that, in rare cases, dataslayer will report a tag as being "via GTM" when there is no such tag in the GTM container. This seems to happen when GTM is used for most of the implementation and a client has added something directly to the site that leverages gtag.js.

I've included a screencap of dataslayer with the mystery event called out. I've also included a text file of the script that seems to be sending that event.
[lftracker_script.txt](https://github.com/sean-adams/dataslayer/files/2928254/lftracker_script.txt)
![dataslayer_screencap](https://user-images.githubusercontent.com/40038892/53763902-81c71a00-3e91-11e9-9c53-31b0007163c9.png)

The "via GTM" note in dataslayer is misleading and could be an issue for clients who have lots of tags. On our site, I was able to verify that it wasn't in our GTM container because we only have 18 tags right now; however, for a client with 150+ tags, it would be harder to check where the event is coming from.

**Comment by sean-adams** [comment]
@rptomey thanks for reporting this! This is a particularly interesting item that I haven't run across before, and will probably end up as a "won't fix" because of the same thing that makes it interesting... but I'd like to hear your feedback.

Let's start with a bit about where the "via GTM" note in dataslayer comes from.

Dataslayer detects that a GA tag has been fired from GTM by looking for a ```gtm``` parameter (which contains a variation of the GTM container ID) in the GA tag. This is set somewhere in the initial creation of the GA tracking object, which is then exposed to the Javascript environment of the page. Once that GA tracking object is created, all tags fired from it will have this ```gtm``` parameter set.

Normally, this is fine, even in more complicated variations, like:
- if there were an additional GA object on the page itself that *wasn't* created by GTM (e.g. hard-coded analytics.js), it wouldn't have that set, and the parameter wouldn't appear in those calls
- if there were an additional GTM container creating its own additional GA object, it would set the ```gtm``` parameter appropriately to the other container ID

Where it gets interesting is: the tracking script you shared piggybacks on the existing GA tracking object rather than creating its own. Because the only GA tracking object it can find is the one that was created by GTM (and therefore has this ```gtm``` value set), every tag that it fires using that tracking object looks to dataslayer like it was fired by GTM (because, in a sense, *it was* - it was fired by a 3rd party script using the GA object **created by** GTM - but dataslayer has no visibility into this chain of events).

So, it's a bit of a weird situation.

From the implementer's perspective, this tag wasn't fired through GTM, but from a technical perspective, it kind of *was* fired through GTM (in that it was fired through the GA object which wouldn't be there in the first place if GTM hadn't created it; and if it were firing through a GA object that *hadn't* been created by GTM, you wouldn't be seeing the "via GTM" note). In that sense, the issue you're seeing will probably never be "fixable", insofar as there's no way that I know of for dataslayer to differentiate a GA tag fired by GTM from a tag that lives outside of GTM and piggybacks on GTM's copy of GA.

That being said, I do also appreciate that the "via GTM" note you're seeing for this tag is factually incorrect from the implementer's perspective. Would being able to disable that note in the settings be of any help?

**Comment by rptomey** [comment]
Hey Sean,

Thank you for your thorough explanation! I really appreciate the communication model of "first here's all the information you need to know about _X_ in order to understand the reason for _Y_" and try to use that with my own clients.

I'd never noticed the "gtm" parameter in the collect request's query string. I understand completely now why it's a "won't fix", and I don't think being able to disable the note in settings is necessary.

I'm closing this issue so that you can check it off your list. I really appreciate that you taught me something new about GA collection, and I continue to appreciate how much easier your extension has made my job.

Ryan

**Comment by sean-adams** [comment]
@rptomey thanks for the kind words and glad you found it helpful! And thanks back at you for sharing plenty of info in your initial report which helped me figure this out quickly.
