### ISSUE TITLE
there is console.log in the code -- console.log('** dataslayer: injecting Launch monitors **')

### ISSUE THREAD

**Issue by AitorAlejandro** [sean-adams/dataslayer#71]
**Please include, if available:**
- the URL of the page with an error
- the dataslayer export, if possible (click the file icon on the right of the panel, then export to a JSON file)
- any errors in the console for the page
- any errors in the console (and, if possible, the full log) for dataslayer (you can access this by right-clicking in the dataslayer panel, clicking "Inspect", and looking in the new DevTools instance that pops up)
- your Chrome version and dataslayer version

If you don't feel comfortable posting any of this information publicly (e.g. it contains sensitive client data), please email to info@dataslayer.org.

**Comment by sean-adams** [comment]
Hi @AitorAlejandro - is this causing issues? Since dataslayer has to inject into the page context, the idea here is to provide some level of warning for developers who may wish to understand e.g. why `window._satellite` is already defined outside of their code. But if this is leading to problems I'm happy to reconsider.

**Comment by AitorAlejandro** [comment]
No problem whatsoever Sean. I thought it was a forgetting.

**Comment by sean-adams** [comment]
Thanks Aitor no problem!
