### ISSUE TITLE
Events don't being detected in angular

### ISSUE THREAD

**Issue by Musty-dev** [sean-adams/dataslayer#97]
I'm developing an app with angular that needs to use GTM. When I do the initial push it goes ok, but when I do other pushes, dataslayer doesn't detect anything.

I do this:

`
window['dataLayer'] = window['dataLayer'] || [];
window['dataLayer'].push(payload);
`

The first time dataslayer detects it, but when I do another push, it's not showing it.

It's a problem of my app or a dataslayer problem?

**Comment by sean-adams** [comment]
hi @Musty-dev - better support for single page apps is planned for the future, but I'd like to learn more about the issue you're experiencing right now, because this is probably a dataslayer problem. Does this happen with every push after the initial push? Or does it only happen after route changes?
